import "./globals.css";
import { Raleway } from "src/fonts";
import bg from "../../public/images/bg.webp";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={Raleway.className}
        style={{
          // backgroundImage: `linear-gradient(#000b, #000b), url(${bg.src})`,
          background: '#000'
        }}
      >
        {children}
      </body>
    </html>
  );
}
