import "./globals.css";
import { NT } from "src/fonts";
import bg from "../../public/images/bg.webp"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={NT.className} style={{backgroundImage: `linear-gradient(#0008, #0008), url(${bg.src})`}}>{children}</body>
    </html>
  );
}
