import "./globals.css";
import { NT } from "src/fonts";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={NT.className}>{children}</body>
    </html>
  );
}
